### ISSUE TITLE
Questions about Interactivity API usage

### ISSUE THREAD

**Issue by luisherranz** [djuric/tabs#1]
First, congratulations on the block. It's very well done and works wonderfully 🙂

I hope it's not rude on my part, but I have some questions about how you've used the Interactivity API. Not with the intention of criticizing, but rather to understand how people use the Interactivity API and which parts might be more intuitive and which less intuitive, with the sole aim of improving the API and/or the documentation.

1. Why do you need to do client-side navigation?
  Each time there is a navigation, I don't see any new information generated on the server that is not present on the initial page. It's true that it works this way, and it could even be seen as an elegant way to do it, but it's also true that you're making an 
unnecessary request to the server. Could you let me know why you chose this approach instead of saving the active tab in the 
client state, and simply change that state when the user clicks on a tab?
2. Why did you use `data-wp-each` to render the tab buttons?
  As the number of tabs is not dynamic and never changes in the client, I wonder why you have used `data-wp-each` instead of a PHP `for` loop.

That's it. Thank you very much! 🙏

**Comment by djuric** [comment]
Hey @luisherranz

Thank you very much for all the kind words! I really value the work you are doing on Interactivity API and feedback from you is always welcome :) 

Let me address each of your points:

### 1. Client-side navigation

My primary goal here is to apply client-side navigation in a real-world scenario. I found tabs to be a solid use-case for this. That said, you are absolutely right - all the information is already available on the initial page. 

A more efficient approach would be to load the content of each tab on-demand. For example, only the content of the first tab could be rendered on the initial page load, and when a user clicks another tab, only then fetch and replace the existing tab content dynamically. I just modified the logic to use that approach and it seems to be working quite well, you can take a look at [this MR](https://github.com/djuric/tabs/pull/2)

### 2. PHP loop instead of `data-wp-each`

Here are some of the reasons why I opted for  `data-wp-each`:

- `getContext()` provides current tab automatically and I can just use code like `context.tab.isActive = true` to reference current tab. With PHP loop,  I would need to manually assign something like a data-id to each tab, then handle event passing to determine which tab is currently active.

- The synax `data-wp-class--active="context.tab.isActive"` is convenient to write and it also won't strip the existing class. With PHP, the code has to be written with something like `class="<?php echo $tab['isActive'] ? 'wp-block-tabs-tabs__navigation-item active' : 'wp-block-tabs-tabs__navigation-item'; ?>"`

I opened another [MR ](https://github.com/djuric/tabs/pull/3) so you can compare the difference between these two methods. Is there a processing overhead compared to rendering the same element with a PHP loop? 

Thank you again for taking the time to share your thoughts!

**Comment by luisherranz** [comment]
> A more efficient approach would be to load the content of each tab on-demand. 

Correct. In that case, the use of client-side navigation would be justified. 

However, keep in mind that if you don't include the content of the tabs in the HTML, Google won't index it (something to consider from an SEO perspective).

> Here are some of the reasons why I opted for data-wp-each:

So, mostly developer experience. Thank you! 🙂

> Is there a processing overhead compared to rendering the same element with a PHP loop?

A very small one, yes.

**Comment by djuric** [comment]
I appreciate your feedback, thank you!

**Comment by luisherranz** [comment]
Thanks to you, Žarko, for exploring the Interactivity API. If you ever have more questions or create more blocks, don't hesitate to share them with us 🙂
